[package]
name = "strong-xml-test-suite"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4"
env_logger = "0.8"
log = "0.4"
strong-xml = { path = "../strong-xml", features = ["log"] }
